### ISSUE TITLE
Subscribe example script with loop_forever doesn't work

### ISSUE THREAD

**Issue by scls19fr** [denglerchr/Mosquitto.jl#19] opened 2024-02-29 08:41 UTC
Hello,

Example https://github.com/denglerchr/Mosquitto.jl/blob/main/examples/07_loop_forever.jl only displays

    Connection of client 6BApxz7wOpbK13E successfull (MOSQ_ERR_SUCCESS), subscribing to test/#

no message are received (while I can see some messages with 

    mosquitto_sub -h test.mosquitto.org -t "test/#"

Moreover CTRL+C (or +D or +Q) doesn't quit example (I need to close console window)

OS : Windows 10
julia version 1.10.1

Kind regards

PS : I should have started with this before trying reactive notebook as mentioned in https://github.com/denglerchr/Mosquitto.jl/issues/15

**Comment by scls19fr** [comment] 2024-02-29 08:42
I should have started with this before trying reactive notebook as mentioned in #15

**Comment by denglerchr** [comment] 2024-03-01 12:46
Will be difficult to find, as it works for me on Windows. `versioninfo()`:
```
Julia Version 1.10.1
Commit 7790d6f064 (2024-02-13 20:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 16 × 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, tigerlake)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)
```
I will probably replace this one with loop_forever2 in the next version release. Unfortunately I had a bug in loop_forever2, else I would recommend you use that one. Fixed it in master though.

**Comment by scls19fr** [comment] 2024-03-01 13:28
I can confirm that it works fine with `loop_forever2`.

**Comment by denglerchr** [comment] 2024-05-03 05:20
I removed export from `loop_forever` in 0.9 and recommend using `loop`, which can do everything `loop_forever` can. Since I also cant seem to reproduce the issue with `loop_forever` Im closing this one for now.

**Closed by denglerchr** 2024-05-03 05:20 UTC
